[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "matt"
version = "0.0.1"
authors = [
    {name = "Salvatore Ingala", email = "salvatoshi@protonmail.com"},
]
description = "Merkleize All The Things"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["covenant", "smart contracts", "bitcoin"]
license = { file = "LICENSE" }
dependencies = []

[tool.poetry.dev-dependencies]
bokeh = "^3.3.4"
networkx = "^3.2.1"
numpy = "^1.26.4"
pytest = "^6.2.5"
