name: Python Test Suite

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-24.04
    container: bigspider/bitcoin_matt
    steps:
      - name: Prepare Configuration File
        run: |
          mkdir -p /github/home/.bitcoin
          cp /root/.bitcoin/bitcoin.conf /github/home/.bitcoin/bitcoin.conf
      - name: Run MATT-enabled bitcoind
        run: |
          bitcoind -regtest --daemon
      - name: Set up dependencies
        run: |
          apt-get update
          apt-get install -y libssl-dev libffi-dev
          apt-get install -y python3-venv
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Clone
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install .
        shell: bash
      - name: Create test wallet
        run: bash ./examples/init.sh
      - name: Run tests and capture output
        run: |
          source venv/bin/activate
          pytest -vv
        shell: bash
      - name: Upload test output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test_output.txt
      - name: Upload markdown report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: report.md
          path: report.md
