name: Python Test Suite

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-20.04
    container: bigspider/bitcoin_matt
    steps:
      - name: Prepare Configuration File
        run: |
          mkdir -p /github/home/.bitcoin
          cp /root/.bitcoin/bitcoin.conf /github/home/.bitcoin/bitcoin.conf
      - name: Run MATT-enabled bitcoind
        run: |
          bitcoind -regtest --daemon
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Clone
        uses: actions/checkout@v2
      - name: Install pip and pytest
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip install -r requirements-dev.txt
      - name: Install pymatt
        run: |
          pip install .
      - name: Create test wallet
        run: bash ./examples/init.sh
      - name: Add repository root to PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Run tests and capture output
        run: pytest -vv
      - name: Upload test output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: test_output.txt
      - name: Upload markdown report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: report.md
          path: report.md
