name: Python Test Suite

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-24.04
    container: bigspider/bitcoin_matt
    steps:
      - name: Prepare Configuration File
        run: |
          mkdir -p /github/home/.bitcoin
          cp /root/.bitcoin/bitcoin.conf /github/home/.bitcoin/bitcoin.conf
      - name: Run MATT-enabled bitcoind
        run: |
          bitcoind -regtest --daemon
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        run: uv python install 3.10
      - name: Set up virtual environment
        run: uv venv --python 3.10
      - name: Load development dependencies
        run: |
          source .venv/bin/activate
          uv sync --dev
          deactivate
        shell: bash
      - name: Create test wallet
        run: ./examples/init.sh
        shell: bash
      - name: Run tests and capture output
        run: |
          source .venv/bin/activate
          pytest -vv
          deactivate
        shell: bash
      - name: Upload test output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test_output.txt
      - name: Upload markdown report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: report.md
          path: report.md
